/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geraldo.quiz2;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALDO
 */
public class Panel extends javax.swing.JFrame {

    private int id = 0;
    private String code;
    private DefaultTableModel TBLmodel;
    private DefaultComboBoxModel CBmodel;
    private ArrayList<Item> brg = new ArrayList<>();
   
    
    public Panel() {
        initComponents();
        Toko toko = new Toko();
        this.CBmodel = new DefaultComboBoxModel<>(toko.getJenisNama().toArray());
        TblTransaksi tbltransaksi = new TblTransaksi();
        this.TBLmodel = new DefaultTableModel(tbltransaksi.getKolomNama(),0);
        initComponents();
        
        TFcode.setEnabled(false);
        BTadd.setEnabled(false);
        BTremove.setEnabled(false);
        CBitems.setEnabled(false);
        BTsave.setEnabled(false);
        BTcancel.setEnabled(false);
        TBLtransaksi.setEnabled(false);
        TFjml.setEnabled(false);
        
        
    }
    
    private void IncreamentId(){
    this.id += 1;
    }
    
    private void DecreamentId(){
        this.id -= 1;
    }
    
    private Object[] addItem(String nama , int jumlah){
        float harga = 0;
        Toko items = new Toko();
        for(int i = 0 ; i < items.getHargaBarang().size();i++){
            if(nama.equalsIgnoreCase(items.getJenisNama().get(i))){
                harga = items.getHargaBarang().get(i);
            }
        }
        Object[] ob = {
            nama,
            harga,
            jumlah
        };
        return ob;
    } 
    
    private void updateJumlah(String nama,int add){
    ArrayList<String> item = new ArrayList<>();
    for(int i = 0;i < TBLmodel.getRowCount();i++){
        item.add(TBLmodel.getValueAt(i, 0).toString());
    }
    for(int i = 0;i < item.size();i++){
        if(item.get(i).equals(nama)){
            int jumlah = new Integer (TBLmodel.getValueAt(i,2).toString());
            TBLmodel.setValueAt(jumlah + add, i,2);
        }
    }
    }
    
    private boolean Duplicate(String nama){
        boolean result = false;
        ArrayList<String> item = new ArrayList<>();
        for(int i = 0; i < TBLmodel.getRowCount();i++){
            item.add(TBLmodel.getValueAt(i,0).toString());
        }
        for(String i : item){
            if(i.equals(nama)){
                result = true;
            }
        }
        return result;
    }
    
    private void belanja(){
        if(isEmpty()){
            this.BTsave.setEnabled(false);
            this.BTremove.setEnabled(false);
        }else{
            this.BTremove.setEnabled(true);
            this.BTremove.setEnabled(true);
        }
    }
    
    private boolean isEmpty(){
        return this.TBLtransaksi.getModel().getRowCount() <=0;
    }
    
    private void newTransaksi(){
        this.TFjml.setText("");
        this.TFcode.setText("");
        this.BTnew.setEnabled(false);
        this.BTsave.setEnabled(false);
        this.BTcancel.setEnabled(false);
        this.BTadd.setEnabled(false);
        this.BTremove.setEnabled(false);
        this.TFjml.setEnabled(false);
        this.CBitems.setEnabled(false);
        this.TBLmodel.setRowCount(0);
        this.brg.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTnew = new javax.swing.JButton();
        BTadd = new javax.swing.JButton();
        BTremove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CBitems = new javax.swing.JComboBox<>();
        TFjml = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLtransaksi = new javax.swing.JTable();
        BTsave = new javax.swing.JButton();
        BTcancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTnew.setText("New");
        BTnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTnewActionPerformed(evt);
            }
        });

        BTadd.setText("Add");
        BTadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaddActionPerformed(evt);
            }
        });

        BTremove.setText("Remove");
        BTremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTremoveActionPerformed(evt);
            }
        });

        jLabel1.setText("Code");

        jLabel2.setText("Items");

        TFjml.setText("1");

        TBLtransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(TBLtransaksi);

        BTsave.setText("Save");
        BTsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsaveActionPerformed(evt);
            }
        });

        BTcancel.setText("Cancel");
        BTcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TFcode, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(BTnew, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTremove, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTsave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CBitems, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFjml, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTnew))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTadd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(CBitems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TFjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTremove)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTsave)
                    .addComponent(BTcancel))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTnewActionPerformed
        // TODO add your handling code here:
          int i = 0;
          i++; 
        
       BTadd.setEnabled(true);
       BTcancel.setEnabled(true);
       BTremove.setEnabled(true);
       BTsave.setEnabled(true);
       CBitems.setEnabled(true);
       TFjml.setEnabled(true);
       TBLtransaksi.setEnabled(true);
       
       Date d = new Date();
       SimpleDateFormat sdf = new SimpleDateFormat("yyMMdd");
       String dateStr = sdf.format(d);
       
       TFcode.setText(dateStr + "0" + i);
       BTnew.setEnabled(false);
       
        
    }//GEN-LAST:event_BTnewActionPerformed

    private void BTaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaddActionPerformed
        // TODO add your handling code here:
        String nama = this.CBitems.getSelectedItem().toString();
        int jumlah = new Integer(this.TFjml.getText());
        if(Duplicate(nama)){
            updateJumlah(nama,jumlah);
        }else{
            TBLmodel.addRow(addItem(nama,jumlah));
        }
        this.belanja();
    }//GEN-LAST:event_BTaddActionPerformed

    private void BTsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsaveActionPerformed
        // TODO add your handling code here:
        try{
            for(int i = 0; i < TBLmodel.getRowCount();i++){
                String nama = TBLmodel.getValueAt(i, 0).toString();
                float harga = new Float(TBLmodel.getValueAt(i, 1).toString());
                int jumlah = new Integer(TBLmodel.getValueAt(i,2).toString());
               this.brg.add(new Item(nama,harga,jumlah));
            }
            Transaksi transaksi = new Transaksi(this.code,this.brg);
            StringBuilder sbr = new StringBuilder();
            sbr.append(transaksi.Pembayaran());
            JOptionPane.showMessageDialog(this,sbr,"Transaksi",JOptionPane.INFORMATION_MESSAGE);
            newTransaksi();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BTsaveActionPerformed

    private void BTcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcancelActionPerformed
        // TODO add your handling code here:
        newTransaksi();
        this.DecreamentId();
    }//GEN-LAST:event_BTcancelActionPerformed

    private void BTremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTremoveActionPerformed
        // TODO add your handling code here:
        if(TBLtransaksi.getSelectedRow() < 0){
            String sbr = "Pilih item mau di hapus";
            JOptionPane.showMessageDialog(this,sbr,"Informasi",JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            int count = TBLtransaksi.getSelectedRows().length;
            for(int i = 0;i < count;i++){
                TBLmodel.removeRow(TBLtransaksi.getSelectedRow());
            }
        }
        this.belanja();
    }//GEN-LAST:event_BTremoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTadd;
    private javax.swing.JButton BTcancel;
    private javax.swing.JButton BTnew;
    private javax.swing.JButton BTremove;
    private javax.swing.JButton BTsave;
    private javax.swing.JComboBox<String> CBitems;
    private javax.swing.JTable TBLtransaksi;
    private javax.swing.JTextField TFcode;
    private javax.swing.JTextField TFjml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
